# Generated by Django 5.2.7 on 2026-02-10 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AccesoModulos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'permissions': [('ver_eps', 'Puede ver el módulo de EPS'), ('ver_certificados', 'Puede ver el módulo de Certificados Laborales'), ('ver_incapacidades', 'Puede ver el módulo de Incapacidades')],
                'managed': False,
            },
        ),
    ]
